apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meu-site
  template:
    metadata:
      labels:
        app: meu-site
    spec:
      containers:
        - name: nginx
          image: meu-site-nginx:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80

